const ContractStatus = {
  IN_PROGRESS: 'PROCESSING',
  WAIT_PARTNER: 'WAITINGFORPARTNER',
  AUTHENTICATIONFAIL: 'AUTHENTICATIONFAIL',
  FINISH: 'COMPLETE',
  EXPIRED: 'EXPIRED',
  CANCEL: 'CANCEL',
};
export default ContractStatus;
