class AUTH_ACTION {
  static SET_USER = 'AUTH/SET_USER';
  static SET_LOADING_PROFILE = 'AUTH/SET_LOADING_PROFILE';
  static SET_LOGGED_OUT = 'AUTH/SET_LOGGED_OUT';
  

}
class MENU_ACTION {
  static LOAD = 'theme/LOAD';
}

class DATA_ACTION {
  static SET_LOADING_DATA = 'DATA/SET_LOADING_DATA';
  static SET_STATISTICS = 'DATA/SET_STATISTICS';
  static SET_TAGS = 'DATA/SET_TAGS';
  static SET_RELOAD_CONTRACT = 'DATA/SET_RELOAD_CONTRACT';
  static SET_READY_FOR_RELOAD_STATISTICS = 'DATA/SET_READY_FOR_RELOAD_STATISTICS';
  static SET_IS_DISCONNECT = 'DATA/SET_IS_DISCONNECT';
  static SET_UNREAD_NOTIFICATION = 'DATA/SET_UNREAD_NOTIFICATION';
  static SET_ACTIVE_TAB_NOTIFICATION = 'DATA/SET_ACTIVE_TAB_NOTIFICATION';
}

class DETAIL_CONTRACT_ACTION {
  static SET_CONTRACT = 'DETAIL_CONTRACT_ACTION/SET_CONTRACT';
  static UPDATE_CONTRACT = 'DETAIL_CONTRACT_ACTION/UPDATE_CONTRACT';
  static SET_COMMENTS = 'DETAIL_CONTRACT_ACTION/SET_COMMENTS';
  static SET_NEW_COMMENT = 'DETAIL_CONTRACT_ACTION/SET_NEW_COMMENT';
  static SET_START_COMMENT = 'DETAIL_CONTRACT_ACTION/SET_START_COMMENT';
  static SET_FOCUS_COMMENT = 'DETAIL_CONTRACT_ACTION/SET_FOCUS_COMMENT';
  static CREATE_NEW_COMMENT = 'DETAIL_CONTRACT_ACTION/CREATE_NEW_COMMENT';
  static ADD_NEW_COMMENT = 'DETAIL_CONTRACT_ACTION/ADD_NEW_COMMENT';
  static ADD_NEW_NOTIFICATION = 'DETAIL_CONTRACT_ACTION/ADD_NEW_NOTIFICATION';
  static REMOVE_NOTIFICATION = 'DETAIL_CONTRACT_ACTION/REMOVE_NOTIFICATION';
  static SET_CURRENT_SIGNER = 'DETAIL_CONTRACT_ACTION/SET_CURRENT_SIGNER';
  static SET_CURRENT_SIGNER_TOKEN = 'DETAIL_CONTRACT_ACTION/SET_CURRENT_SIGNER_TOKEN';
  static ADD_CHILD_COMMENT = 'DETAIL_CONTRACT_ACTION/ADD_CHILD_COMMENT';
  static ADD_COMMENT = 'DETAIL_CONTRACT_ACTION/ADD_COMMENT';
  static SET_PREVIEW_CURRENT_PAGE = 'DETAIL_CONTRACT_ACTION/SET_PREVIEW_CURRENT_PAGE';
  static SET_PREVIEW_TOTAL_PAGES = 'DETAIL_CONTRACT_ACTION/SET_PREVIEW_TOTAL_PAGES';
  static SET_PDF_CURRENT_PAGE = 'DETAIL_CONTRACT_ACTION/SET_PDF_CURRENT_PAGE';
  static SET_PDF_TOTAL_PAGES = 'DETAIL_CONTRACT_ACTION/SET_PDF_TOTAL_PAGES';
  static RESET_DATA = 'DETAIL_CONTRACT_ACTION/RESET_DATA';
  static SET_CONTRACT_TAGS = 'DETAIL_CONTRACT_ACTION/SET_CONTRACT_TAGS';
  static SET_NOTIFICATIONS_UNREAD = 'DETAIL_CONTRACT_ACTION/SET_NOTIFICATIONS_UNREAD';
  static UPDATE_NOTIFICATIONS = 'DETAIL_CONTRACT_ACTION/UPDATE_NOTIFICATIONS';
  static UPDATE_COMMENTS = 'DETAIL_CONTRACT_ACTION/UPDATE_COMMENTS';
  static SET_SHOW_SIGNER_MODAL = 'DETAIL_CONTRACT_ACTION/SET_SHOW_SIGNER_MODAL';
  static SET_FOCUS_SIGN = 'DETAIL_CONTRACT_ACTION/SET_FOCUS_SIGN';
  static SET_CANCELING = 'DETAIL_CONTRACT_ACTION/SET_CANCELING';
  static SET_LOADED_ALL_PAGE_DETAIL = 'DETAIL_CONTRACT_ACTION/SET_LOADED_ALL_PAGE_DETAIL';
  static SET_LOADED_ALL_PAGE_PREVIEW_DETAIL = 'DETAIL_CONTRACT_ACTION/SET_LOADED_ALL_PAGE_PREVIEW_DETAIL';
  static SET_IS_DISCONNECT = 'DETAIL_CONTRACT_ACTION/SET_IS_DISCONNECT';
  static SET_FOCUS_REALTIME_COMMENT = 'DETAIL_CONTRACT_ACTION/SET_FOCUS_REALTIME_COMMENT';
}

class NOTIFICATION_ACTION {
  static SET_NOTIFICATIONS = 'NOTIFICATION/SET_NOTIFICATIONS';
  static ADD_NOTIFICATION = 'NOTIFICATION/ADD_NOTIFICATION';
  static REMOVE_NOTIFICATION = 'NOTIFICATION/REMOVE_NOTIFICATION';
  static UPDATE_ALL_NOTIFICATIONS = 'NOTIFICATION/UPDATE_ALL_NOTIFICATIONS';

  static SET_NEW_CONTRACT_NOTIFICATIONS = 'NOTIFICATION/SET_NEW_CONTRACT_NOTIFICATIONS';
  static UPDATE_NEW_CONTRACT_NOTIFICATIONS = 'NOTIFICATION/UPDATE_NEW_CONTRACT_NOTIFICATIONS';
  static SET_COMMENT_NOTIFICATIONS = 'NOTIFICATION/SET_COMMENT_NOTIFICATIONS';
  static UPDATE_COMMENT_NOTIFICATIONS = 'NOTIFICATION/UPDATE_COMMENT_NOTIFICATIONS';
  static SET_EXPIRE_NOTIFICATIONS = 'NOTIFICATION/SET_EXPIRE_NOTIFICATIONS';
  static UPDATE_EXPIRE_NOTIFICATIONS = 'NOTIFICATION/UPDATE_EXPIRE_NOTIFICATIONS';
  static UPDATE_STATUS_NOTIFICATIONS = 'NOTIFICATION/UPDATE_STATUS_NOTIFICATIONS';
}

class CREATE_CONTRACT_ACTION {
  static SET_STEP = 'CREATE_CONTRACT/SET_STEP';
  static SET_FILE = 'CREATE_CONTRACT/SET_FILE';
  static SET_FILE_URL = 'CREATE_CONTRACT/SET_FILE_URL';
  static SET_SIGNERS = 'CREATE_CONTRACT/SET_SIGNERS';
  static ADD_SIGNER = 'CREATE_CONTRACT/ADD_SIGNER';
  static UPDATE_SIGNER = 'CREATE_CONTRACT/UPDATE_SIGNER';
  static UPDATE_SIGNER_POSITION = 'CREATE_CONTRACT/UPDATE_SIGNER_POSITION';
  static REMOVE_SIGNER = 'CREATE_CONTRACT/REMOVE_SIGNER';
  static SET_INFORMATION = 'CREATE_CONTRACT/SET_INFORMATION';
  static SET_PREVIEW_CURRENT_PAGE = 'CREATE_CONTRACT/SET_PREVIEW_CURRENT_PAGE';
  static SET_PREVIEW_TOTAL_PAGES = 'CREATE_CONTRACT/SET_PREVIEW_TOTAL_PAGES';
  static SET_PDF_CURRENT_PAGE = 'CREATE_CONTRACT/SET_PDF_CURRENT_PAGE';
  static SET_PDF_TOTAL_PAGES = 'CREATE_CONTRACT/SET_PDF_TOTAL_PAGES';
  static SET_CREATING_CONTRACT = 'CREATE_CONTRACT/SET_CREATING_CONTRACT';
  static SET_READY_FOR_CREATING = 'CREATE_CONTRACT/SET_READY_FOR_CREATING';
  static RESET_DATA = 'CREATE_CONTRACT/RESET_DATA';
}

class NEW_CONTRACT_ACTION {
  static SET_NEW_CONTRACTS = 'NEW_CONTRACT/SET_NEW_CONTRACTS';
  static SET_READY_FOR_RELOADING = 'NEW_CONTRACT/SET_READY_FOR_RELOADING';
}
class ALERT_MODAL_ACTION {
  static SET_MODAL = "ALERT_MODAL/SET_MODAL";
}
class INSTALL_TOOL_MODAL_ACTION {
  static SET_INSTALL_TOOL_MODAL = "INSTALL_TOOL_MODAL/SET_INSTALL_TOOL_MODAL"
}
class ALERT_TOAST_ACTION {
  static ADD_TOAST = 'ALERT_TOAST/ADD_TOAST';
  static REMOVE_TOAST = 'ALERT_TOAST/REMOVE_TOAST'
}
class LIST_CONTRACT_ACTION {
  static SET_LIST_CONTRACTS = 'LIST_CONTRACT/SET_LIST_CONTRACT';
  static SET_READY_FOR_RELOADING = 'LIST_CONTRACT/SET_READY_FOR_RELOADING';
  static SET_IS_CANCELING = 'LIST_CONTRACT/SET_IS_CANCELING';
  static SET_GLOBAL_SIGNING = 'LIST_CONTRACT/SET_GLOBAL_SIGNING'
}

export {
  DATA_ACTION,
  AUTH_ACTION, MENU_ACTION, DETAIL_CONTRACT_ACTION, NOTIFICATION_ACTION, CREATE_CONTRACT_ACTION, NEW_CONTRACT_ACTION, LIST_CONTRACT_ACTION,
  ALERT_MODAL_ACTION, INSTALL_TOOL_MODAL_ACTION, ALERT_TOAST_ACTION
};
