runtime: java
env: flex

runtime_config:  # Optional
  jdk: openjdk8

handlers:
- url: /.*
  script: this field is required, but ignored

manual_scaling:
  instances: 1

env_variables:
  JAVA_OPTS: -Dspring.profiles.active=pro
  PROFILER_ENABLE: true

resources:
  memory_gb: 2.0

